# NAME - AKSHAT SHRIVASTAVA
# ROLL - 2305591
# SECTION= CSE-35
# SET -1

Write a Python program to input weight in grams and
convert it into kilograms and grams.

In [32]:
w= int(input("enter weight in gram "))
print("WEIGHT =", w//1000 ,"Kg and", w%1000 , "grams")



WEIGHT = 12 Kg and 345 grams


 2.Write a Python program to print a diamond pattern using
 alphabets. Accept number of rows from user (maximum 5).

In [26]:
n = int(input("Enter number of rows (max 5): "))

if n < 1 or n > 5:
    print("Invalid input")
else:
    letters = "ABCDE"


    for i in range(n):
        print(" " * (n - i - 1), end="")
        print((letters[i] + " ") * (i + 1))


    for i in range(n - 2, -1, -1):
        print(" " * (n - i - 1), end="")
        print((letters[i] + " ") * (i + 1))


    A 
   B B 
  C C C 
 D D D D 
E E E E E 
 D D D D 
  C C C 
   B B 
    A 



3.Write a recursive function to find the product of numbers
from 1 to n, but skip every third number.
For example: for n=5, calculate 1 × 2 × 4 × 5


In [28]:
def function(n):
    if n == 0:
        return 1

    if n % 3 == 0:
        return function(n - 1)
    else:
        return n * function(n - 1)

function(5)

40

4. Create a program to manage a contact list using dictionary.
Each contact should have name, phone numbers (multiple),
email, and category (family/friend/work). Include functions
to:
- Add new contact
- Add additional phone number to existing contact
- Search by name or phone number
- Display contacts by category

In [36]:
contacts = {}


def add_contact():
    name = input("Enter name: ")

    if name in contacts:
        print("Contact already exists")
        return

    phone = input("Enter phone number: ")
    email = input("Enter email: ")
    category = input("Enter category (family/friend/work): ")

    contacts[name] = {
        "phones": [phone],
        "email": email,
        "category": category
    }

    print("Contact added successfully")


def add_phone():
    name = input("Enter contact name: ")

    if name not in contacts:
        print("Contact not found")
        return

    phone = input("Enter new phone number: ")

    if phone in contacts[name]["phones"]:
        print("Phone number already exists")
        return

    contacts[name]["phones"].append(phone)
    print("Phone number added")


def search_contact():
    query = input("Enter name or phone number to search: ")

    if query in contacts:
        print(query, "->", contacts[query])
        return

    for name, details in contacts.items():
        if query in details["phones"]:
            print(name, "->", details)
            return

    print("Contact not found")


def display_by_category():
    cat = input("Enter category: ")
    found = False

    for name, details in contacts.items():
        if details["category"] == cat:
            print(name, "->", details)
            found = True

    if not found:
        print("No contacts in this category")


while True:
    print("\n1. Add Contact")
    print("2. Add Phone Number")
    print("3. Search Contact")
    print("4. Display by Category")
    print("5. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        add_contact()
    elif choice == "2":
        add_phone()
    elif choice == "3":
        search_contact()
    elif choice == "4":
        display_by_category()
    elif choice == "5":
        print("Exiting program")
        break
    else:
        print("Invalid choice")



1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
Invalid choice

1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
Contact added successfully

1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
AKSHT -> {'phones': ['123456'], 'email': 'WDCW@gmail.com', 'category': 'WOKR'}

1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
No contacts in this category

1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
Invalid choice

1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
No contacts in this category

1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
Phone number added

1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
Invalid choice

1. Add Contact
2. Add Phone Number
3. Search Contact
4. Display by Category
5. Exit
Exiting

5> Using NumPy, create a program that:
 - Creates a 5×5 checkerboard pattern matrix with 1s and 0s
- Rotates it 45 degrees
- Calculates the sum of elements in each quadrant
- Finds the coordinates of all 1s in the rotated matrix
Sample Output:
Original Checkerboard:
[[1 0 1 0 1]
[0 1 0 1 0]
[1 0 1 0 1]
[0 1 0 1 0]
[1 0 1 0 1]]
Rotated Matrix:
[[0 0 1 0 0]
[0 1 0 1 0]
[1 0 1 0 1]
[0 1 0 1 0]
[0 0 1 0 0]]
Quadrant Sums:
Top-Left: 2
Top-Right: 2
Bottom-Left: 2
Bottom-Right: 2
Coordinates of 1s:
[(0,2), (1,1), (1,3), (2,0), (2,2), (2,4), (3,1), (3,3), (4,2)]

In [35]:
import numpy as np


checkerboard = np.array([
    [1, 0, 1, 0, 1],
    [0, 1, 0, 1, 0],
    [1, 0, 1, 0, 1],
    [0, 1, 0, 1, 0],
    [1, 0, 1, 0, 1]
])

print("Original Checkerboard:")
print(checkerboard)


rotated = np.zeros((5, 5), dtype=int)

for i in range(5):
    for j in range(5):
        if checkerboard[i][j] == 1:
            rotated[(i + j)//2][(j - i)//2 + 2] = 1

print("\nRotated Matrix:")
print(rotated)


mid = 5 // 2

top_left = rotated[:mid, :mid].sum()
top_right = rotated[:mid, mid+1:].sum()
bottom_left = rotated[mid+1:, :mid].sum()
bottom_right = rotated[mid+1:, mid+1:].sum()

print("\nQuadrant Sums:")
print("Top-Left:", top_left)
print("Top-Right:", top_right)
print("Bottom-Left:", bottom_left)
print("Bottom-Right:", bottom_right)


coords = list(map(tuple, np.argwhere(rotated == 1)))

print("\nCoordinates of 1s:")
print(coords)


Original Checkerboard:
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]

Rotated Matrix:
[[0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 1 1]
 [0 1 1 1 0]
 [0 0 1 0 0]]

Quadrant Sums:
Top-Left: 1
Top-Right: 1
Bottom-Left: 1
Bottom-Right: 1

Coordinates of 1s:
[(np.int64(0), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(3)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(2), np.int64(3)), (np.int64(2), np.int64(4)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(2))]


6> Create a DataFrame to analyze monthly expense data with
categories (Food, Transport, Utilities, Entertainment,
Others). Write program to:
- Calculate percentage distribution of expenses
- Compare month-over-month changes
- Identify top 3 expense categories
- Generate monthly budget report

In [31]:
import pandas as pd
data={
    "MONTH" : ['JAN','FEB','MAR','APR','MAY'],
    'FOOD' : [2500,3400,2350,2400,1800],
    'TRASNPORT': [800,400,500,600,200],
    'UTILIIES' :[100,200,100,400,300],
    'ENTERTAINMENT' : [1000,2000,1300,2000,200],
}

df = pd.DataFrame(data)

print("Monthly Expense Data:")
print(df)

numeric_df = df.select_dtypes(include="number")
percentage = numeric_df.div(numeric_df.sum(axis=1), axis=0) * 100


print("\nPercentage Distribution (%):")
print(percentage.round(2))



mov_change = numeric_df.diff()
print("\nMonth-over-Month Changes:")
print(mov_change)


top_3 = numeric_df.sum().sort_values(ascending=False).head(3)

print("\nTop 3 Expense Categories:")
print(top_3)




Monthly Expense Data:
  MONTH  FOOD  TRASNPORT  UTILIIES  ENTERTAINMENT
0   JAN  2500        800       100           1000
1   FEB  3400        400       200           2000
2   MAR  2350        500       100           1300
3   APR  2400        600       400           2000
4   MAY  1800        200       300            200

Percentage Distribution (%):
    FOOD  TRASNPORT  UTILIIES  ENTERTAINMENT
0  56.82      18.18      2.27          22.73
1  56.67       6.67      3.33          33.33
2  55.29      11.76      2.35          30.59
3  44.44      11.11      7.41          37.04
4  72.00       8.00     12.00           8.00

Month-over-Month Changes:
     FOOD  TRASNPORT  UTILIIES  ENTERTAINMENT
0     NaN        NaN       NaN            NaN
1   900.0     -400.0     100.0         1000.0
2 -1050.0      100.0    -100.0         -700.0
3    50.0      100.0     300.0          700.0
4  -600.0     -400.0    -100.0        -1800.0

Top 3 Expense Categories:
FOOD             12450
ENTERTAINMENT     6500
TR